# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  i = 16
  machines = ["sh0n0", "sh0n1", "conf", "mongos", "arbiter"]
  machines.each { |machine| 
    config.vm.define machine do |m|
      m.vm.box = "ubuntu/bionic64"
      m.vm.network "public_network", ip: "192.168.18." + i.to_s, bridge: ENV['NETINT']
      i += 1
      m.vm.provider "virtualbox" do |vb|
        vb.cpus = 1
        vb.memory = "512"
      end
      m.vm.provision "shell" do |s|
        ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
        s.inline = <<-SHELL
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
        SHELL
      end
    end
  }
end

